server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud01?useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
